# Generated by Django 5.0.6 on 2024-06-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='desig',
            field=models.CharField(default='user', max_length=15),
        ),
    ]
