# Generated by Django 5.0.6 on 2024-09-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_register_desig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
        migrations.RemoveField(
            model_name='register',
            name='desig',
        ),
    ]
