# Generated by Django 5.0.6 on 2024-09-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delete_userregister_remove_register_desig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='fullname',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
