# Generated by Django 5.0.6 on 2024-09-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_register_id_alter_register_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
